steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/wevr-507318/aidnd/frontend:latest"
      - "--build-arg"
      - "VITE_CORE_API_URL=/api"
      - "--build-arg"
      - "VITE_TRS_URL=/trs"
      - "--build-arg"
      - "VITE_FIREBASE_API_KEY=AIzaSyC_tZgGj1e5Hzg8fup1H-1ha6dtJxYIAdc"
      - "--build-arg"
      - "VITE_FIREBASE_AUTH_DOMAIN=ai-dnd-47eb0.firebaseapp.com"
      - "--build-arg"
      - "VITE_FIREBASE_PROJECT_ID=ai-dnd-47eb0"
      - "--build-arg"
      - "VITE_FIREBASE_STORAGE_BUCKET=ai-dnd-47eb0.firebasestorage.app"
      - "--build-arg"
      - "VITE_FIREBASE_MESSAGING_SENDER_ID=160893345729"
      - "--build-arg"
      - "VITE_FIREBASE_APP_ID=1:160893345729:web:e13c970aab8cf141761940"
      - "--build-arg"
      - "VITE_MEASUREMENT_ID=G-WPB1MFYGG4"
      - "."
images:
  - "us-central1-docker.pkg.dev/wevr-507318/aidnd/frontend:latest"
