"""initial schema (squashed)

Revision ID: 001_initial_schema
Revises:
Create Date: 2026-09-08

Squashed from the 14 incremental migrations that preceded this one.
Autogenerated from app.db.models (Base.metadata) against an empty
database and verified to produce zero further diff — this is the exact
schema the application's ORM models describe today. Safe to squash: no
production data exists yet to preserve across the old migration history.
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "001_initial_schema"
down_revision: str | None = None
branch_labels: list[str] | None = None
depends_on: list[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("auth_provider_id", sa.String(length=255), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("current_refresh_jti", sa.String(length=36), nullable=True),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("avatar_url", sa.String(length=1024), nullable=True),
        sa.Column("banner_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_index(
        op.f("ix_users_auth_provider_id"), "users", ["auth_provider_id"], unique=True
    )
    op.create_table(
        "scenarios",
        sa.Column(
            "scenario_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("logline", sa.String(length=150), nullable=True),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column(
            "world_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=20), server_default="draft", nullable=False
        ),
        sa.Column(
            "genre_tags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("complexity_tier", sa.String(length=20), nullable=False),
        sa.Column("player_count_support", sa.String(length=20), nullable=False),
        sa.Column("estimated_playtime", sa.String(length=50), nullable=True),
        sa.Column("cover_image_url", sa.String(length=1024), nullable=True),
        sa.Column("content_tag", sa.String(length=100), nullable=True),
        sa.Column("publish_error", sa.Text(), nullable=True),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("play_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "rating_avg",
            sa.Numeric(precision=3, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("narrator_persona", sa.Text(), nullable=True),
        sa.Column(
            "setup_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "state_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "end_conditions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "checkpoints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("current_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("opening_scene", sa.Text(), nullable=True),
        sa.Column("narration_font", sa.String(length=50), nullable=True),
        sa.Column(
            "action_chips",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "setup_archetypes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "complexity_tier IN ('newbie', 'intermediate', 'master')",
            name=op.f("ck_scenarios_ck_scenarios_complexity_tier"),
        ),
        sa.CheckConstraint(
            "mode IN ('newbie', 'master')", name=op.f("ck_scenarios_ck_scenarios_mode")
        ),
        sa.CheckConstraint(
            "player_count_support IN ('solo', 'multiplayer', 'both')",
            name=op.f("ck_scenarios_ck_scenarios_player_count_support"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'publishing', 'published', 'publish_failed', 'archived')",
            name=op.f("ck_scenarios_ck_scenarios_status"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.user_id"],
            name=op.f("fk_scenarios_creator_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("scenario_id", name=op.f("pk_scenarios")),
    )
    op.create_index(
        "idx_scenarios_genre_tags",
        "scenarios",
        ["genre_tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "bookmarks",
        sa.Column("bookmark_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_bookmarks_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_bookmarks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bookmark_id", name=op.f("pk_bookmarks")),
        sa.UniqueConstraint(
            "user_id", "scenario_id", name="uq_bookmarks_user_scenario"
        ),
    )
    op.create_table(
        "end_conditions",
        sa.Column(
            "end_condition_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column(
            "condition_expression",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("outcome_tag", sa.String(length=10), nullable=False),
        sa.Column("outcome_title", sa.String(length=255), nullable=False),
        sa.Column("outcome_text", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_end_conditions_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("end_condition_id", name=op.f("pk_end_conditions")),
    )
    op.create_index(
        "idx_end_conditions_scenario_priority",
        "end_conditions",
        ["scenario_id", "priority"],
        unique=False,
    )
    op.create_table(
        "entities",
        sa.Column(
            "entity_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("obtainable", sa.Boolean(), nullable=True),
        sa.Column(
            "attributes_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("narrator_instruction", sa.Text(), nullable=True),
        sa.Column("is_player", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_entities_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("entity_id", name=op.f("pk_entities")),
    )
    op.create_index(
        "idx_entities_scenario_id", "entities", ["scenario_id"], unique=False
    )
    op.create_table(
        "music_generation_jobs",
        sa.Column(
            "job_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("mood", sa.String(length=20), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("preview_url", sa.String(length=2048), nullable=True),
        sa.Column("key", sa.String(length=20), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','failed')",
            name=op.f("ck_music_generation_jobs_ck_music_generation_jobs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.user_id"],
            name=op.f("fk_music_generation_jobs_creator_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_music_generation_jobs_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_music_generation_jobs")),
    )
    op.create_table(
        "music_generation_log",
        sa.Column(
            "log_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.user_id"],
            name=op.f("fk_music_generation_log_creator_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_music_generation_log_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("log_id", name=op.f("pk_music_generation_log")),
    )
    op.create_table(
        "playthroughs",
        sa.Column(
            "playthrough_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("checkpoint", sa.String(length=255), nullable=True),
        sa.Column("turn_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
        sa.Column("scenario_version", sa.Integer(), nullable=False),
        sa.Column(
            "scenario_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ended_outcome_tag", sa.String(length=10), nullable=True),
        sa.Column("ended_outcome_title", sa.String(length=255), nullable=True),
        sa.Column("ended_outcome_text", sa.Text(), nullable=True),
        sa.Column("is_playtest", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ended_outcome_tag IN ('win', 'lose')",
            name=op.f("ck_playthroughs_ck_playthroughs_ended_outcome_tag"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'abandoned')",
            name=op.f("ck_playthroughs_ck_playthroughs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.user_id"],
            name=op.f("fk_playthroughs_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_playthroughs_scenario_id_scenarios"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("playthrough_id", name=op.f("pk_playthroughs")),
    )
    op.create_table(
        "rule_invariants",
        sa.Column(
            "invariant_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "invariant_expression",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("applies_to", sa.String(length=255), nullable=False),
        sa.Column("narrator_text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_rule_invariants_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("invariant_id", name=op.f("pk_rule_invariants")),
    )
    op.create_index(
        "idx_rule_invariants_scenario_id",
        "rule_invariants",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "scenario_conditions",
        sa.Column(
            "condition_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column(
            "condition_expression",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "condition_version",
            sa.String(length=50),
            server_default="1.0",
            nullable=False,
        ),
        sa.Column("narrator_instruction", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "state_mutation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_conditions_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("condition_id", name=op.f("pk_scenario_conditions")),
    )
    op.create_table(
        "scenario_entity_types",
        sa.Column(
            "scenario_entity_type_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("type_key", sa.String(length=30), nullable=False),
        sa.Column("display_label", sa.String(length=60), nullable=False),
        sa.Column(
            "attributes_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_entity_types_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "scenario_entity_type_id", name=op.f("pk_scenario_entity_types")
        ),
        sa.UniqueConstraint(
            "scenario_id", "type_key", name="uq_scenario_entity_types_type_key"
        ),
    )
    op.create_index(
        "idx_scenario_entity_types_scenario_id",
        "scenario_entity_types",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "scenario_maps",
        sa.Column(
            "map_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_maps_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("map_id", name=op.f("pk_scenario_maps")),
    )
    op.create_index(
        "idx_scenario_maps_scenario_id", "scenario_maps", ["scenario_id"], unique=False
    )
    op.create_table(
        "scenario_minigames",
        sa.Column(
            "minigame_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("minigame_type", sa.String(length=20), nullable=False),
        sa.Column(
            "trigger_condition_expression",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column("outcome_mode", sa.String(length=10), nullable=False),
        sa.Column(
            "win_mutation",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "lose_mutation",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "tiered_outcomes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "timeout_mutation",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("narrator_instruction_template", sa.Text(), nullable=True),
        sa.Column(
            "dodge_config",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("replit_embed_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_minigames_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("minigame_id", name=op.f("pk_scenario_minigames")),
    )
    op.create_index(
        "idx_scenario_minigames_scenario_id",
        "scenario_minigames",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "scenario_music",
        sa.Column(
            "scenario_music_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("mood", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("track_url", sa.String(length=2048), nullable=True),
        sa.Column("generation_prompt", sa.String(length=500), nullable=True),
        sa.Column("key", sa.String(length=20), nullable=True),
        sa.Column("bpm", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mood IN ('peaceful','mystery','tension','combat','melancholy','triumph')",
            name=op.f("ck_scenario_music_ck_scenario_music_mood"),
        ),
        sa.CheckConstraint(
            "source IN ('upload','generated','default')",
            name=op.f("ck_scenario_music_ck_scenario_music_source"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_music_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("scenario_music_id", name=op.f("pk_scenario_music")),
        sa.UniqueConstraint(
            "scenario_id", "mood", name="uq_scenario_music_scenario_id_mood"
        ),
    )
    op.create_table(
        "scenario_reviews",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5",
            name=op.f("ck_scenario_reviews_ck_scenario_reviews_rating"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_reviews_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_scenario_reviews_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_scenario_reviews")),
        sa.UniqueConstraint(
            "user_id", "scenario_id", name="uq_scenario_reviews_user_scenario"
        ),
    )
    op.create_table(
        "facts",
        sa.Column(
            "fact_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("subject_entity_id", sa.UUID(), nullable=False),
        sa.Column("predicate", sa.String(length=100), nullable=False),
        sa.Column("object_entity_id", sa.UUID(), nullable=True),
        sa.Column("object_literal", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.String(length=100), nullable=True),
        sa.Column(
            "when_active", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("hidden", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("superseded_fact_id", sa.UUID(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(object_entity_id IS NOT NULL) != (object_literal IS NOT NULL)",
            name=op.f("ck_facts_ck_facts_object_exclusive"),
        ),
        sa.ForeignKeyConstraint(
            ["object_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_facts_object_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_facts_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_facts_subject_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_fact_id"],
            ["facts.fact_id"],
            name=op.f("fk_facts_superseded_fact_id_facts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("fact_id", name=op.f("pk_facts")),
    )
    op.create_index("idx_facts_scenario_id", "facts", ["scenario_id"], unique=False)
    op.create_index(
        "idx_facts_subject_entity_id", "facts", ["subject_entity_id"], unique=False
    )
    op.create_table(
        "map_connections",
        sa.Column(
            "connection_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("entity_id_a", sa.UUID(), nullable=False),
        sa.Column("entity_id_b", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_id_a < entity_id_b",
            name=op.f("ck_map_connections_ck_map_connections_sorted_pair"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id_a"],
            ["entities.entity_id"],
            name=op.f("fk_map_connections_entity_id_a_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id_b"],
            ["entities.entity_id"],
            name=op.f("fk_map_connections_entity_id_b_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_map_connections_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("connection_id", name=op.f("pk_map_connections")),
        sa.UniqueConstraint(
            "scenario_id", "entity_id_a", "entity_id_b", name="uq_map_connections_pair"
        ),
    )
    op.create_index(
        "idx_map_connections_scenario_id",
        "map_connections",
        ["scenario_id"],
        unique=False,
    )
    op.create_table(
        "map_pins",
        sa.Column(
            "pin_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("map_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column(
            "is_start_location", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.entity_id"],
            name=op.f("fk_map_pins_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["map_id"],
            ["scenario_maps.map_id"],
            name=op.f("fk_map_pins_map_id_scenario_maps"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_map_pins_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("pin_id", name=op.f("pk_map_pins")),
    )
    op.create_index("idx_map_pins_map_id", "map_pins", ["map_id"], unique=False)
    op.create_index(
        "idx_map_pins_one_start_per_scenario",
        "map_pins",
        ["scenario_id"],
        unique=True,
        postgresql_where=sa.text("is_start_location"),
    )
    op.create_table(
        "participants",
        sa.Column(
            "participant_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("playthrough_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("turn_order_position", sa.Integer(), nullable=False),
        sa.Column(
            "joined_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'joined')",
            name=op.f("ck_participants_ck_participants_role"),
        ),
        sa.ForeignKeyConstraint(
            ["playthrough_id"],
            ["playthroughs.playthrough_id"],
            name=op.f("fk_participants_playthrough_id_playthroughs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_participants_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("participant_id", name=op.f("pk_participants")),
        sa.UniqueConstraint(
            "playthrough_id", "turn_order_position", name="uq_participants_turn_order"
        ),
        sa.UniqueConstraint(
            "playthrough_id", "user_id", name="uq_participants_playthrough_user"
        ),
    )
    op.create_table(
        "playthrough_shares",
        sa.Column(
            "share_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("share_token", sa.String(length=255), nullable=False),
        sa.Column("playthrough_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode IN ('spectate', 'join')",
            name=op.f("ck_playthrough_shares_ck_playthrough_shares_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["playthrough_id"],
            ["playthroughs.playthrough_id"],
            name=op.f("fk_playthrough_shares_playthrough_id_playthroughs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("share_id", name=op.f("pk_playthrough_shares")),
        sa.UniqueConstraint("share_token", name="uq_playthrough_shares_token"),
    )
    op.create_index(
        "ix_playthrough_shares_token",
        "playthrough_shares",
        ["share_token"],
        unique=False,
    )
    op.create_table(
        "turn_logs",
        sa.Column(
            "turn_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("playthrough_id", sa.UUID(), nullable=False),
        sa.Column("turn_number", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=True),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column("narration_text", sa.Text(), nullable=True),
        sa.Column(
            "tool_calls",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(length=1024), nullable=True),
        sa.Column("location_id", sa.String(length=255), nullable=True),
        sa.Column("scene_image_prompt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.participant_id"],
            name=op.f("fk_turn_logs_participant_id_participants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["playthrough_id"],
            ["playthroughs.playthrough_id"],
            name=op.f("fk_turn_logs_playthrough_id_playthroughs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_turn_logs")),
        sa.UniqueConstraint(
            "playthrough_id", "turn_number", name="uq_turn_logs_playthrough_turn"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("turn_logs")
    op.drop_index("ix_playthrough_shares_token", table_name="playthrough_shares")
    op.drop_table("playthrough_shares")
    op.drop_table("participants")
    op.drop_index(
        "idx_map_pins_one_start_per_scenario",
        table_name="map_pins",
        postgresql_where=sa.text("is_start_location"),
    )
    op.drop_index("idx_map_pins_map_id", table_name="map_pins")
    op.drop_table("map_pins")
    op.drop_index("idx_map_connections_scenario_id", table_name="map_connections")
    op.drop_table("map_connections")
    op.drop_index("idx_facts_subject_entity_id", table_name="facts")
    op.drop_index("idx_facts_scenario_id", table_name="facts")
    op.drop_table("facts")
    op.drop_table("scenario_reviews")
    op.drop_table("scenario_music")
    op.drop_index("idx_scenario_minigames_scenario_id", table_name="scenario_minigames")
    op.drop_table("scenario_minigames")
    op.drop_index("idx_scenario_maps_scenario_id", table_name="scenario_maps")
    op.drop_table("scenario_maps")
    op.drop_index(
        "idx_scenario_entity_types_scenario_id", table_name="scenario_entity_types"
    )
    op.drop_table("scenario_entity_types")
    op.drop_table("scenario_conditions")
    op.drop_index("idx_rule_invariants_scenario_id", table_name="rule_invariants")
    op.drop_table("rule_invariants")
    op.drop_table("playthroughs")
    op.drop_table("music_generation_log")
    op.drop_table("music_generation_jobs")
    op.drop_index("idx_entities_scenario_id", table_name="entities")
    op.drop_table("entities")
    op.drop_index("idx_end_conditions_scenario_priority", table_name="end_conditions")
    op.drop_table("end_conditions")
    op.drop_table("bookmarks")
    op.drop_index(
        "idx_scenarios_genre_tags", table_name="scenarios", postgresql_using="gin"
    )
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_users_auth_provider_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
