"""bookmarks and scenario_reviews

Revision ID: 002_bookmarks_and_reviews
Revises: 001_initial_schema
Create Date: 2026-09-03 03:37:14.291414

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002_bookmarks_and_reviews"
down_revision: str | None = "001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmarks",
        sa.Column("bookmark_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_bookmarks_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_bookmarks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("bookmark_id", name=op.f("pk_bookmarks")),
        sa.UniqueConstraint(
            "user_id", "scenario_id", name="uq_bookmarks_user_scenario"
        ),
    )
    op.create_table(
        "scenario_reviews",
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name="ck_scenario_reviews_rating"
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenarios.scenario_id"],
            name=op.f("fk_scenario_reviews_scenario_id_scenarios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_scenario_reviews_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_scenario_reviews")),
        sa.UniqueConstraint(
            "user_id", "scenario_id", name="uq_scenario_reviews_user_scenario"
        ),
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected pre-existing naming-convention drift on
    # playthrough_shares/users indexes and constraints, unrelated to this
    # migration's purpose (bookmarks/scenario_reviews only) — intentionally
    # left out here rather than silently folded into this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_reviews")
    op.drop_table("bookmarks")
    # ### end Alembic commands ###
